import { authOptions } from '@/lib/next-auth'
import { getServerSession } from 'next-auth'
import { notFound } from 'next/navigation'
import { ReactNode } from 'react'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }: { children: ReactNode }) {
  const session = await getServerSession(authOptions)

  if (!session) {
    notFound()
  }

  return (
    <div className='w-full flex h-screen'>
      {children}
    </div>
  )
}

